### PR TITLE
Specify color of the charts based on the situations

### LINKED ISSUE #9: Fix colors on donut and column stacked chart
Approved courses should always be blue, failed red, and so on. At the moment Google Charts assign default colors and depending on the order the categories are on the data array, they become different colors on the carts.

As there are only a few possible categories, we should search how to hard-code categories and colors on Google Charts.

### PR DESCRIPTION
**Pull request by davidguilherme**
Close #9

### CODE REVIEW

**Comment by fernandobrito** [comment]
Hey @davidguilherme, awesome to see you here! Thanks for the PR! :+1: 

Unfortunately I have reached my 5 apps limit on Heroku, so no review app was created for this pull request.

For me, looks ready for production. @gustavosobral, what do you think?

**Comment by gustavosobral** [comment]
Thanks for commit @davidguilherme! You just forgot to add 'REP. FALTA' situation case on the colors. When you asked me earlier, I forgot this one! Sorry :smile: 

And about the colors, I prefer to keep them something similar to the original Google Charts pallete.
`'APROVADO': '#109618',
'REPROVADO': '#DC3912',
'MATRICULADO': '#3366CC',
'TRANCADO': '#FF9900',
'DISPENSADO': '#949BA2',
'REP. FALTA': '#8B0707'`

**Comment by davidguilherme** [comment]
Hey, guys!

Sorry for the delay. I had a lot of work to do in this week.

**Comment by gustavosobral** [comment]
No problem @davidguilherme! Thanks for the help, and congrats for the awesome solution :clap:.  Hope to see you here again.

**Pull request merged**
